# Generated by Django 6.1.1 on 2026-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_points'], name='accounts_us_total_p_442425_idx'),
        ),
    ]
