# Generated by Django 6.1.1 on 2026-09-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ayah',
            index=models.Index(fields=['surah', 'numberInSurah'], name='quran_ayah_surah_i_11a950_idx'),
        ),
        migrations.AddIndex(
            model_name='ayah',
            index=models.Index(fields=['juz'], name='quran_ayah_juz_594b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='surah',
            index=models.Index(fields=['name'], name='quran_surah_name_b0f3f0_idx'),
        ),
    ]
