# Generated by Django 6.1.1 on 2026-09-21 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('quran', '0002_ayah_quran_ayah_surah_i_11a950_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_correct',
        ),
        migrations.AlterField(
            model_name='session',
            name='challenge_type',
            field=models.CharField(choices=[('random', 'Random challenge'), ('specific', 'Specific challenge')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['challenge_type'], name='game_sessio_challen_3ef4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-created_at'], name='game_sessio_user_id_252c64_idx'),
        ),
    ]
