# Generated by Django 6.1.1 on 2026-09-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_session_is_correct_and_more'),
        ('quran', '0002_ayah_quran_ayah_surah_i_11a950_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='quran.ayah'),
        ),
    ]
