# Generated by Django 6.1.1 on 2026-10-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_session_user_answer'),
        ('quran', '0002_ayah_quran_ayah_surah_i_11a950_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='questions',
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.ayah')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
            ],
        ),
    ]
